---
title: "College Costs"
author: "Eric Fletcher"
date: "8/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Import Data}
#Pulling data from https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-03-10/readme.md

tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')

tuition_income <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv') 

salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')

historical_tuition <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')

diversity_school <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')
```
```{r Import Libraries}
library(tidyverse)
library(scales)
theme_set(theme_light()) #my default theme inspired by the talented David Robinson (https://www.youtube.com/channel/UCeiiqmVK07qhY-wvg3IZiZQ)
```

```{r Raw Data Inspection / Global Manipulations}
##salary_potential seems like a good start

glimpse(salary_potential) #935 rows & 7 columns
summary(salary_potential) #large range between the lowest and highest costs

```

```{r NA Counts}
##NA counts - NAs look good

#tidyverse approach
na_count_tidyverse <- salary_potential %>% 
  summarise_all(~ sum(is.na(.)/nrow(salary_potential))) 

#base approach 
na_counts_base <- sapply(salary_potential, function(x) sum(length(which(is.na(x))))/nrow(salary_potential))

```

```{r EDA Salary Potential - 1}
##Which states produce the highest paid college graduates?

#summary data frame ahead of plotting
foo <- salary_potential %>% 
  select(state_name, early_career_pay, mid_career_pay) %>% 
  group_by(state_name) %>% 
  summarise(median_early_career_pay = median(early_career_pay, na.rm = TRUE),
            median_mid_career_pay = median(mid_career_pay, na.rm = TRUE)) %>% 
  mutate(pay_diff = -(median_early_career_pay - median_mid_career_pay))


foo$state_name <- fct_reorder(foo$state_name, foo$median_mid_career_pay) #reorder state_name by mid career pay in ascending order

bar <- foo %>% 
  select(-pay_diff) %>% 
  pivot_longer(cols = 2:3, names_to = "career_stage", values_to = "median_pay") %>% 
  ggplot(aes(y = state_name)) +
  geom_line(aes(x = median_pay)) +
  geom_point(aes(x = median_pay, fill = career_stage), size = 2, pch = 21)+
  #facet_wrap(~career_stage)+
  scale_x_continuous(labels = scales::dollar)+
  scale_fill_discrete(labels = c("Early", "Middle"))+
  labs(title = "Which States Produce the Highest-Paid College Graduates?",
       subtitle = "Early and Middle Career Pay",
       fill = "Career Stage",
       x = "Median Pay", 
       y = "State",
       caption = "Data: College Salary Report, 2019 | Visualization: @ImmediateFishing8")+
  theme(panel.grid.major.y = element_blank(),
        plot.margin = margin(6,12,6,12),
        #legend.position = "NONE",
        plot.title = element_text(
          #family = "Trochut",
          hjust = 0.5,
          face = "bold",
          #size = 69, 
          color = "black"),
        plot.subtitle = element_text(
          #family = "Trochut",
          hjust = 0.5,
          #face = "bold",
          #size = 48, 
          color = "black"),
       plot.caption = element_text(
         #family = "Tomorrow",
          hjust = 0.5,
          #face = "bold",
          #size = 17, 
          color = "black"))
bar

ggsave("pay_by_career_stage_reddit.png",plot=bar, dpi= 300, type = "cairo")  
```
```{r EDA Salary Potential - 2}
##For each state, what are the colleges that report the highest alumni earnings?

#summary data for use in plotting
foo_2 <- salary_potential %>% 
  select(name, state_name, early_career_pay, mid_career_pay) %>% 
  group_by(state_name) %>% 
  arrange(state_name, (desc(mid_career_pay))) %>% 
  slice(1) %>% 
  arrange(desc(mid_career_pay)) %>% 
  unite(col = state_school, c(state_name, name), sep = " - ")
foo_2 

foo_2$state_school <- fct_reorder(foo_2$state_school, foo_2$mid_career_pay)

foo_2_plot <- foo_2 %>% 
pivot_longer(cols = c(early_career_pay, mid_career_pay), names_to = "pay_stage", values_to = "pay") %>% 
ggplot(aes(y = state_school))+
  geom_line(aes(x = pay))+
  geom_point(aes(x = pay, fill = pay_stage), size = 4, pch = 21)+
  scale_x_continuous(labels = scales::dollar)+
  scale_fill_discrete(labels = c("Early: 0-5 Yr. Exp.", "Middle: 10+ Yr. Exp."))+
  labs(title = "What Colleges Did the Highest Earning Alumni Attend?",
       subtitle = "The Top College Per State by Median Salary in 2019",
       x = "",
       y = "",
       fill = "Career Stage",
       caption = "Data: College Salary Report, 2019 | Visualization: Eric Fletcher")+
  theme(plot.margin = margin(15,20,15,20),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 16),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 14),
        plot.title = element_text(
          #family = "Trochut",
          hjust = 0.5,
          face = "bold",
          size = 19, 
          color = "black"),
        plot.subtitle = element_text(
          #family = "Trochut",
          hjust = 0.5,
          #face = "bold",
          size = 17, 
          color = "black"),
       plot.caption = element_text(
         #family = "Tomorrow",
          hjust = 0.5,
          #face = "bold",
          size = 11, 
          color = "black"))
  
ggsave("pay_by_school_state.png",plot=foo_2_plot, dpi= 300, type = "cairo", width = 13, height = 15)
```
