---
title: "Kamala_Bernie_Voting"
author: "Eric Fletcher"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data}
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)

df <- data.table(Agree=c(93), 
                 Disagree=c(7))

df2 <- df %>% 
        pivot_longer(cols = c("Agree", "Disagree"), names_to = "Vote", values_to = "Percent")
```

```{r plot}
bar <- ggplot(df2, aes(x= "", y=Percent, fill = Vote)) + 
            geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() +
  geom_text(aes(y = Percent, label = paste0(Percent, "%")), color = "black", size=10,
            position = position_stack(vjust = 0.5))+
  labs(title = "How Often Did Kamala Harris Vote with Bernie Sanders in 2017-18",
             caption = "Data: ProPublica | Visualization: Eric Fletcher",
             fill = "Outcome")+
  theme(plot.margin=unit(c(1,1,1,1),"cm"),
    plot.title = element_text(
    hjust = 0.7,
    face = "bold",
    size = 25, 
    color = "black"),
    plot.caption = element_text(
      hjust = 0.5,
      size = 20, 
      color = "black"),
    legend.title = element_text(size = 25, face = "bold"),
    legend.text = element_text(size = 25))
    

ggsave(bar, 
       units = c("in"),
       width = 15,
       height = 12,
       dpi = 300, 
       file="kamala_bernie_voting.png", 
       type="cairo-png")
```
